### PR TITLE
Convert to cljc and reader conditionals

### PR DESCRIPTION
**Pull request by danielcompton**
New attempt, based on #26.

- [ ] Commenting out time related queries because I haven't picked a clj-time replacement for the ClojureScript port (cljs-time looks promising though).
- [ ] Handle UUID's. It [looks](https://groups.google.com/d/topic/clojure/MVkRaPmJq2E) like [this](https://github.com/lbradstreet/cljs-uuid-utils) might be the best option. I would have expected something from Google Closure for this though. Also worth looking at this [gist](https://gist.github.com/franks42/4159427). I think there was a recent release of cljs which supports UUID's as well.
- [ ] Properly handle fn's
- [x] Check Regexs are correct, probably need platform specific versions

### CODE REVIEW

**Comment by danielytics** [comment]
So am I correct in saying that the goal here is that `rethinkdb.query` is available from cljs so that the queries can be constructed in cljs (but actually sending the queries and receiving results is clj only, so only `query.clj` and `query_builder.clj` need to be ported)?

I would suggest maybe adding a `build` function to `rethinkdb.query` that calls `replace-vars` and then modifying `run` to optionally take a prebuilt query.

**Comment by danielcompton** [comment]
I need to check this, but I'm pretty sure we don't need to modify `run` at all. Calling `(-> (r/db) (r/table :users))` will generate EDN data. That can be shipped across to the server where it calls `(r/run client-query conn)`.

**Comment by danielcompton** [comment]
Regex's aren't being used anymore on the shared path after b1433fa.

**Comment by danielcompton** [comment]
I've merged this into master. There are however a few caveats:
* `fn` isn't supported in CLJS
* `order-by` isn't supported in CLJS

I'll open tickets to fix these separately.

**Comment by danielytics** [comment]
I suppose it depends on if you want to call `replace-vars` as part of the AST building, or as part of running (on the server, later). If you're happy with the latter, then it works as is.

Great work, btw.

**Comment by danielcompton** [comment]
I haven't really looked at fn, what's the difference between doing it on the client or server?

**Comment by danielytics** [comment]
Nothing much, its just a question of do you want to prepare the query as much as possible (ie the AST is as baked and prepared as possible) or if you just care that the representation is captured.

If you don't want to, say, store the most processed form of a query ready to send to the RethinkDB server and only care that you can create queries from cljs (and store them or whatever), then no changes are necessary.

All `replace-vars` does is make sure that unique integer ID's are assigned to variables that shadow others of the same name in nested scopes.

I suspect the answer is that you just want to be able to generate the query in cljs but don't care that (slightly) more processing is needed before running the query :) so I don't think anything needs to be done. I just wanted to check to be sure.

**Comment by danielcompton** [comment]
Right, makes sense. Probably just as easy to leave it to be done on the server, it should have an added benefit of being slightly easier to debug if we have variable names in them.

**Comment by danielytics** [comment]
Agreed. Like I said, I just wanted to make sure it was thought about. I don't mind which way you choose, but you're right that doing it on the server would be better for debugging, so lets do that.

**Comment by arichiardi** [comment]
Hello guys, sorry if I write in a closed issue, but how to start with ClojureScript? I tried `[rethinkdb.query :as r :include-macros true]` but I saw there is an `IllegalArgumentException` no in a `clj` block in there. Shall I patch it? Maybe the question is more like, what is this namespace missing in terms of reader conditionals?

**Comment by apa512** [comment]
A patch would be great. ```IllegalArgumentException``` is probably the only thing that has to be changed. I totally forgot about ClojureScript when adding that.

**Pull request merged**
