### PR TITLE
replace zipmap across keys, vals

### PR DESCRIPTION
**Pull request by sritchie**
There was a discussion recently on the clojure mailing list about how "keys" and "vals" are NOT guaranteed to return items in the same order for a given map. Let's get ahead of the game and fix this up here. Thoughts?

### CODE REVIEW

**Comment by mike-thompson-day8** [comment]
I was under the impression that the mailing list discussion confirmed that `keys` and `vals`  WILL return items in the same order, **for the one map**. 

For reference, I believe this is the discussion:
https://groups.google.com/forum/#!topic/clojure/rqBQ-2Ad4LM

**Comment by danielytics** [comment]
My reading of it is the same.

As Ambrose points out, the [documentation notes](https://github.com/clojure/clojure/blob/028af0e0b271aa558ea44780e5d951f4932c7842/src/clj/clojure/core.clj#L1478) that `(keys m)` and `(vals m)` returns the same order as `(seq m)`, so as long as `m` is the same map (which it is in this case), I don't think there's any issues.

**Comment by sritchie** [comment]
Great, works for me. My bad on remembering wrong.



—

**Comment by danielytics** [comment]
Thanks for putting in the work to fixing it, even if it didn't technically need fixing :)

**Comment by apa512** [comment]
Interesting stuff. So we agree that the current implementation works as intended?

**Comment by sritchie** [comment]
Yup, agreed. Okay to close.



—

**Pull request closed without merging**
