### PR TITLE
implement Closeable

### PR DESCRIPTION
**Pull request by sritchie**
Implements Closeable for connections.

### CODE REVIEW

**Comment by sritchie** [comment]
Here's another attempt. I couldn't extend `clojure.lang.Atom` since the class is marked final, so I wrapped the atom in a record and extended `Closeable` and `IDeref` for good measure.

**Comment by sritchie** [comment]
I also added a `.travis.yml` so we can get travis-ci to run the tests for free on every pull request and build. If that's something you're into I can help get it set up for this repo.

**Comment by apa512** [comment]
Looks good but I'm getting some exceptions when running the tests:
```
                       rethinkdb.core.Connection/close                          core.clj:   39
                                  rethinkdb.core/close                          core.clj:   28
                         rethinkdb.net/send-stop-query                           net.clj:   88
                              rethinkdb.net/send-query                           net.clj:   69
                                    clojure.core/swap!                          core.clj: 2234
java.lang.NullPointerException:
```
Will look into this more when I get a chance.

**Comment by sritchie** [comment]
Huh, they're passing for me with `lein test` and running them locally at the repl. Is this with a fresh repl instance?

**Comment by sritchie** [comment]
Thanks for taking the time!

**Comment by apa512** [comment]
You're right. I was trying to make the Cursor type more seq like (e.g. implement equiv) and must have messed up somewhere else.

Merged now. Great changes :+1:

**Comment by sritchie** [comment]
Nice! For sure. I'm just starting to play around with rethink. Really happy this library's here.

**Pull request merged**
