### PR TITLE
Add connect and read timeouts to sockets.

### PR DESCRIPTION
**Pull request by aphyr**
rethinkdb.core/conn doesn't use timeouts for either opening connections
or its read operations, and most socket ops are uninterruptible. This
can lead to thread and socket exhaustion when the server is
nonresponsive. This patch introduces :conn-timeout and :read-timeout
options, both defaulting to 5000 ms, for core/conn.

### CODE REVIEW

**Comment by apa512** [comment]
Great! Released as 0.12.2-SNAPSHOT.

**Comment by aphyr** [comment]
You're welcome! Thanks @apa512. :)

**Comment by dignati** [comment]
Hi @aphyr, Using this commit we run into issue when using the connection more than 5 seconds (the timeout) after creating it. The test for #128 fails for exactly this reason, yours didn't because the test server was fast enough. This issue is [easily reproducible](https://gist.github.com/dignati/22561d463d20d497358d) and results is one thread spinning endlessly and a unusable connection.

@apa512 I think this commit should be reverted unless it's your intention that connections can't be used after 5 seconds of inactivity.

**Comment by aphyr** [comment]
Huh! I've been using this in a program that uses the same connection for twenty minutes without a problem--I wonder if the issue is related to *inactivity*--perhaps there's an async thread constantly performing socket reads that doesn't handle SocketTimeoutException correctly?
On Jan 21, 2016 09:27, Ole Krüger <notifications@github.com> wrote:Hi @aphyr, Using this commit we run into issue when using the connection more than 5 seconds (the timeout) after creating it. The test for #128 fails for exactly this reason, yours didn't because the test server was fast enough. This issue is easily reproducible and results is one thread spinning endlessly and a unusable connection.

@apa512 I think this commit should be reverted unless it's your intention that connections can't be used after 5 seconds of inactivity.

**Comment by dignati** [comment]
Yes, it seems to be inactivity that triggers this behaviour. I'm not sure
how to debug further, I'm a bit out of my depth

Kyle Kingsbury <notifications@github.com> schrieb am Do., 21. Jan. 2016,
19:23:

**Comment by aphyr** [comment]
Well I'm pretty sure we want socket timeouts--without them I've seen rethink client programs with hundreds of threads stuck in socketinputstream.read0 which will never terminate, and with this patch those threads give up correctly when the server's unavailable. I'll poke around in the codebase and see what the read path looks like.
On Jan 21, 2016 10:34, Ole Krüger <notifications@github.com> wrote:Yes, it seems to be inactivity that triggers this behaviour. I'm not sure
how to debug further, I'm a bit out of my depth

Kyle Kingsbury <notifications@github.com> schrieb am Do., 21. Jan. 2016,
19:23:

**Pull request merged**
