### PR TITLE
Update #'rethinkdb.query/filter to allow optargs

### PR DESCRIPTION
**Pull request by yurrriq**
Per the [docstring][1]:

> By default RethinkDB will ignore documents where a specified field is missing.
> Passing ```{:default (r/error)}``` as an optional argument will cause any
> non-existence error to raise an exception.

Currently, something like...
```clojure
(r/filter sq predicate {:default true})
```
...throws an exception:

> Wrong number of args (3) passed to: query/filter

[1]: https://github.com/apa512/clj-rethinkdb/blob/fb1423fafc6cc4c5e487d744f40c424e54ba3882/src/rethinkdb/query.clj#L180-L182

### CODE REVIEW

**Comment by danielcompton** [comment]
@yurriq could you add tests to cover this new feature as well? (Reminds me to add tests to my open PRs)

**Comment by yurrriq** [comment]
For sure.

**Comment by yurrriq** [comment]
I added a basic test that fails on 80f7da01981043d72ffe70b7d84d3513ecc43121 and passes on yurrriq/clj-rethinkdb@7927c6c767bc61cd336d9d4cc373ea624cb5b843, but I'm not thrilled by it...

Any ideas for improvement are most welcome.

**Comment by danielcompton** [comment]
Hey sorry for the delay on this, I've been away. I'll try and get to it in the next few days.

**Comment by yurrriq** [comment]
Sounds good.

**Comment by danielcompton** [comment]
This all looks pretty good, there's a few more things this needs before it's ready, but I'm happy to help/do the work on these:

- [ ] Update the docstring to match http://rethinkdb.com/api/javascript/filter/, e.g. 
> * If default is set to true, documents with missing fields will be returned rather than skipped.
> * If default is set to r.error(), an RqlRuntimeError will be thrown when a document with a missing field is tested.
> * If default is set to false (the default), documents with missing fields will be skipped.

- [ ] Add test cases for all three defaults
- [ ] Modify existing test case to not use `:bool true`, and to filter on something different. To someone who wasn't familiar with filter, it looks like we're setting a default *value* (is `:bool` is not found, it equals true), rather than default *behaviour* (skipping/including record)

**Comment by yurrriq** [comment]
I merged in [master][1], [updated the docstring][2] and [modified/added tests][3]. Let me know what you think.

[1]: https://github.com/apa512/clj-rethinkdb/tree/master
[2]: https://github.com/apa512/clj-rethinkdb/commit/513ee4b84ced9249ba0c31896dc925fafd358ac1
[3]: https://github.com/apa512/clj-rethinkdb/commit/d351cd4b577fa49c489cbbaab490f80bab2a3f77

**Comment by danielcompton** [comment]
Hey this looks great! Thanks so much.

**Comment by yurrriq** [comment]
Cheers!

**Pull request merged**
