### PR TITLE
Alternative unsweetened interface to FUNC

### PR DESCRIPTION
**Pull request by rplevy**
Hi,

This PR solves a problem for me, but I as I'll describe below it makes this library more usable and versatile in general, which is why I'm submitting it for your consideration. :)

While it can be helpful to mirror the signature of clojure.core/fn for creating a FUNC term, as is done in the rethinkdb.query/fn syntactic sugar macro, it presents some problems in practice.  Namely when constructing a somewhat complex term it becomes a hassle that the argument to fn is a free symbol (because fn is defined as a macro).  This means that it can be necessary to write a macro just to be able to use r.q/fn in such a situation. Obviously that's not really worth it, so in practice you end up going for the term functions in r.q-b directly, and you end up having to write essentially the function I've submitted in this PR. 

Feel free to change things of course to fit your sensibilities.  I called the ns "unsweetened" in reference to the absence of syntactic sugar, per the example of other libraries such as midje and others that use the term "sweet" in this way when offering alternative non-macro interfaces.  I called the function rethink-fn to make it clearer that it was not as directly inspired by clojure.core/fn as r.q/fn is.  The arg list is keywords, as is the case internally, and instead of a body without specified arity, a single term expression is expected/required.

Let me know what you think!

### CODE REVIEW

**Comment by danielcompton** [comment]
Hey thanks for this. I'll take a deeper look soon, but I like your thinking and approach. Definitely appreciate the tests too :)

The only thing that jumps out as me is that this is in its own namespace. I think it could probably live quite happily in `rethinkdb.query` unless there's a reason it needs to go elsewhere?

Thanks!

**Comment by danielytics** [comment]
:+1: I definitely like this too and love how simple the implementation appears to be, but I would also suggest moving it into the `rethinkdb.query` namespace.

**Comment by rplevy** [comment]
Great! Thanks for the quick feedback. I renamed and moved it into query.  (Also, I realized when I went to refactor fn to use the function implementation that I had misunderstood the need for code-walking. That actually belongs in the macro for replacing the symbols with keywords.  The function-only interface now is actually only putting the term in a term map for FUNC.)

**Comment by danielytics** [comment]
Yes, the code walking is just so that `replace-vars` can find them (they get turned into unique integers in the final JSON AST sent to RethinkDB)

That looks good anyway. `func` is a good name for it :)

**Comment by danielcompton** [comment]
I've rebased this PR and squashed the commits against master, then pushed it. All finished. Thanks!

**Pull request closed without merging**
