### PR TITLE
Core async channel API

### PR DESCRIPTION
**Pull request by danielcompton**
This PR adds support for a core.async channel API. It also rearranges a few things to make them tidier and easier to use from two different run functions. Of particular note, **this upgrades protocol support to v4**. This gives us the benefit of "long-polling" the TCP socket when we are `:CONTINUE`ing, rather than having to keep sending queries every 500ms. More detail about this is at https://github.com/rethinkdb/rethinkdb/issues/4400#issuecomment-112222084

This PR isn't finished yet, in particular it needs

- [ ] Documentation and a docstring, including a discussion of backpressure
- [x] Update the changelog
- [ ] Tests
- [ ] Testing from other people
- [ ] A better understanding of the failure cases and how to recover from them. There is an :error-channel provided, but nothing will ever be put on it presently
- [ ] A way to shut down queries *and* close the core.async channel the user is reading from when the connection is closed
- [ ] Discussion about the API for this, in particular about how to provide channels and arity order. Should the user be able to provide an `:error-channel` and `:control-channel` too?
- [x] Probably moving `run-query-chan` to the `rethinkdb.query` namespace or adding a helper function
- [ ] Discussion about a possible future async and current sync run API's. I think it might work well to build the other two on top of the core.async channel API, as there is subtle logic around `:CONTINUE` queries and we don't want to do this more than once. Alternatively I can imagine that there could be an async API which the other two layer on top of, but I'm not sure how it would actually work with `:CONTINUE` queries.
- [ ] Discussion about using manifold instead of core.async for async work.
- [ ] Testing of v4 protocol differences with v3
- [ ] Fix broken tests

### CODE REVIEW

**Comment by apa512** [comment]
Cool. I will look at this soon. :sleeping: now.

**Comment by danielcompton** [comment]
After using the API, I think it would probably be helpful to pass the type of message to the user, so they can dispatch on it as they need.

**Comment by danielytics** [comment]
I think layering sync on top of channel-based api is the right approach. You're right, we don't want to be duplicating the response handling code. At the very least, this should be factored into its own function so at least both places call common code.

Looks good over all. We can discuss in #20

**Comment by danielcompton** [comment]
Continued on #55.

**Pull request closed without merging**
